name: Build Flatpak Repository

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:45
      options: --privileged
    permissions:
      contents: write

    strategy:
      max-parallel: 1
      matrix:
        manifest:
          - build-aux/org.project_spiel.SpielIt.json
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: project-spiel/project-spiel.github.io
          ssh-key: ${{ secrets.WEBSITE_KEY }}
          ref: gh-pages
          path: website

      - name: Setup repo directory
        run: |
          mkdir -p website/repo
          ln -s website/repo repo
  
      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Install org.freedesktop.Platform
        run: flatpak install --noninteractive flathub org.freedesktop.Platform//23.08

      - name: Install org.freedesktop.Sdk
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk//23.08

      - name: Build
        id: build
        uses: andyholmes/flatter@main
        with:
          files: ${{ matrix.manifest }}
          arch: x86_64
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          cache-key: ''

      - name: Deploy
        run: |
          cd website
          git config --global user.email "me@project-spiel.org"
          git config --global user.name "Spiel Robot"
          git add repo
          git commit -m "Updated eSpeak-NG packages"
          git push -f origin gh-pages
          
  